# Opciones de la JVM que usa Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Compilacion en paralelo y cache para que sea mas rapida
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX es obligatorio en proyectos modernos
android.useAndroidX=true

# No generar recursos que no se usan
android.nonTransitiveRClass=true
